{% set name = "cspice" %}
{% set version = "67" %}
{% set root_url = "https://naif.jpl.nasa.gov/pub/naif/misc/toolkit_N%(version)04d/C"|format(version=version | int) %}

{% set file_ext = "tar.Z" %}  # [not win]
{% set file_ext = "zip" %}  # [win]
{% set platform_segment = "PC_Linux_GCC_64bit" %}                                      # [linux64 or aarch64]
{% set sha256 = "60a95b51a6472f1afe7e40d77ebdee43c12bb5b8823676ccc74692ddfede06ce" %}  # [linux64 or aarch64]
{% set platform_segment = "PC_Windows_VisualC_64bit" %}                                # [win64]
{% set sha256 = "98d60b814b412fa55294aeaaeb7dab46d849cc87a8b709ffe835d08de17625dc" %}  # [win64]
{% set platform_segment = "MacIntel_OSX_AppleC_64bit" %}                               # [osx]
{% set sha256 = "6f4980445fee4d363dbce6f571819f4a248358d2c1bebca47e0743eedfe9935e" %}  # [osx]
{% set platform_segment = "MacM1_OSX_clang_64bit" %}                                   # [osx-arm64]
{% set sha256 = "0deae048443e11ca4d093cac651d9785d4f2594631a183d85a3d58949f4d0aa9" %}  # [osx-arm64]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: {{ root_url }}/{{ platform_segment }}/packages/{{ name }}.{{ file_ext }}
  sha256: {{ sha256 }}
  
  patches:
    - 0003_remove_m64_linux.patch  # [linux64 or aarch64]

build:
  number: 7

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - tcsh  # [not win]

test:
  requires:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}

  files:
    - test_cspice.c
  
  commands:
    - "version" 
    - "chronos"
    - "$CC test_cspice.c -I$PREFIX/include -L$PREFIX/lib -lcspice -o test_cspice -Wl,-rpath,$PREFIX/lib"  # [not win]
    - "otool -L test_cspice"  # [not win] 
    - "LD_LIBRARY_PATH=$PREFIX/lib ./test_cspice"  # [not win] 

  downstreams:
    - spiceypy >= 5.0.0

about:
  home: https://naif.jpl.nasa.gov/naif/toolkit.html
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'NASA ancillary information system'

  description: |
      SPICE is an ancillary information system that provides scientists and
      engineers the capability to include space geometry and event data into
      mission design, science observation planning, and science data analysis
      software.
  doc_url: https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/C/index.html

extra:
  recipe-maintainers:
    - astrojuanlu
    - AndrewAnnex
