{% set name = "cspice" %}
{% set version = "67" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # either a tarball or git tag
  git_url: https://github.com/AndrewAnnex/cspice-cmake-spiceypy.git
  git_rev: v0.0.6

build:
  number: 9

requirements:
  build:
    - cmake
    - ninja
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
test:
  requires:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}

  files:
    - test_cspice.c
  
  commands:
    - "version" 
    - "chronos"
    - "$CC test_cspice.c -I$PREFIX/include -L$PREFIX/lib -lcspice -o test_cspice -Wl,-rpath,$PREFIX/lib"  # [not win]
    - "otool -L test_cspice"  # [osx] 
    - "ldd ./test_cspice"  # [linux64 or aarch64]
    - "LD_LIBRARY_PATH=$PREFIX/lib ./test_cspice"  # [not win] 

  downstreams:
    - spiceypy >= 5.0.0

about:
  home: https://naif.jpl.nasa.gov/naif/toolkit.html
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'NASA ancillary information system'

  description: |
      SPICE is an ancillary information system that provides scientists and
      engineers the capability to include space geometry and event data into
      mission design, science observation planning, and science data analysis
      software.
  doc_url: https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/C/index.html

extra:
  recipe-maintainers:
    - astrojuanlu
    - AndrewAnnex
