appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: S7MAGsG7CQNyFrtD1oz3OKay0IXh5tKpVDLmTP2rTg0pqKThxaDTptjT8cQlYe/Yvk4dtjmgfrxHVwOmoYFAaYcJcZhQRSPZ6z1gqBsm6r5vatiyKW7vlcUs2c9JCGnj2/pIOPTf9t+60GGHM9OB/1QKIDtZJc8c9IKN7dWIbidVsKSItt7s2GXaTnlXZ4L4mz4gqmb4fmxMtwKo2sKZt0zZCYDKT+P3f8zcLhGQEvpgdd9iZ0M9DxeTZamA2Y/kfrlc3EBQhEk4MdaA1dyBbh8GJ/J+93+1wZiD0qpGi9/hCuA5i7fWGRG79yKzftv4FqoUNm56u3TaqVJpQlUF6P1Jk2IkQV6yeT6OPb9vrOTmkiBY1esLGtTGeergXmnowDhX/eE8A+AjnO1gCkegJLUdY00UkOlq8e66hQlw1l2l9OmdN7y316CHGu7NrWMnMj7O1YJxy5yugDqHfYdqgwPlrMVazE5SmQFkHE/KW7MYnOHSu46CrFgs3CD/HumRp6oPkDgfHeJJdz494p8wFfHED5ORLdm1BY0M4sy8aPbFsELPzt1OfW31CCdK+8Jtc49Q33l1g1DB+n+nhpGY1THPmr546GVEQpKrXdUdttIexWtXtjnulgCleNwhkRXfaWgucnwf0RNoZ9S/MC16dmbz/MDQ+0a41YPoy1nfnn4=}
provider:
  linux: azure
  osx: azure
  win: azure
  linux_aarch64: default
conda_forge_output_validation: true
